---

# ---------- runtime configuration

gridlinker_admin_connection: "{{ CONNECTION }}"
gridlinker_admin_prefix: "/{{ gridlinker_admin_name }}"
gridlinker_admin_servers: [ "{{ identity.name }}" ]

gridlinker_admin_authority: "{{ SHORT_NAME }}-etcd-clients"
gridlinker_admin_common_name: "{{ identity_name }}"

gridlinker_admin_ca_certificate: "{{
  '/authority/' + gridlinker_admin_authority + '/certificate'
}}"

gridlinker_admin_managed_projects: []

# ---------- configuration files

gridlinker_admin_config: "{{ gridlinker_admin_target }}/config"

gridlinker_admin_directories:

  - directory: "{{ gridlinker_admin_config }}"
    mode: "0755"

gridlinker_admin_config_templates:

  - target: "{{ gridlinker_admin_config }}/connections.yml"
    template: "gridlinker-admin-connections"
    mode: "0644"

  - target: "{{ gridlinker_admin_config }}/overrides.yml"
    template: "gridlinker-admin-connections"
    mode: "0644"

gridlinker_admin_credentials:

  - target: "{{ gridlinker_admin_config }}/{{ gridlinker_admin_name }}-ca.cert"
    source: "{{ gridlinker_admin_ca_certificate }}"
    mode: "0644"

  - target: "{{ gridlinker_admin_config }}/{{ gridlinker_admin_name }}.cert"
    source: "{{ gridlinker_admin_certificate }}"
    mode: "0644"

  - target: "{{ gridlinker_admin_config }}/{{ gridlinker_admin_name }}.key"
    source: "{{ gridlinker_admin_private_key }}"
    mode: "0600"

# ---------- installation

gridlinker_admin_name: "{{ NAME }}"
gridlinker_admin_repository: "{{ METADATA.project.repository }}"
gridlinker_admin_branch: "master"
gridlinker_admin_target: "/home/ubuntu/{{ gridlinker_admin_name }}"

gridlinker_admin_system_packages:

  - "git"

# ex: et ts=2 filetype=yaml
