---

- name: "write php upstart config"
  sudo: "yes"
  notify:
    - "reload upstart config"
    - "set php.needs_restart to 'yes'"
  action:

    module: "template"
    src: "php-upstart"
    dest: "/etc/init/php5-fpm.conf"

- name: "restart php"
  when: "php_needs_restart == 'yes'"
  changed_when: "True"
  notify: "restart php"
  update_resource: {}

- meta: "flush_handlers"

- name: "start php"
  when: "php_state == 'enabled'"
  sudo: "yes"
  action:

    module: "service"
    name: "php5-fpm"
    state: "started"

- name: "stop php"
  when: "php_state == 'disabled'"
  sudo: "yes"
  action:

    module: "service"
    name: "php5-fpm"
    state: "stopped"

# ex: et ts=2 filetype=yaml
