---

- name: "reload upstart config"
  shell: "initctl reload-configuration"
  sudo: "yes"

- name: "set icinga.needs_restart to 'yes'"
  when: "icinga_state == 'enabled'"
  changed_when: "True"
  notify: "restart icinga"
  update_resource:

    icinga.needs_restart: "yes"

- name: "restart icinga"
  when: "icinga_state == 'enabled'"
  notify: "set icinga.needs_restart to 'no'"
  sudo: "yes"
  action:

    module: "service"
    name: "icinga"
    state: "restarted"

- name: "set icinga.needs_restart to 'no'"
  changed_when: "True"
  update_resource:

    icinga.needs_restart: "no"

# ex: et ts=2 filetype=yaml
