---

- name: "reload upstart config"
  shell: "initctl reload-configuration"
  sudo: "yes"

- name: "set mysql.needs_restart to 'yes'"
  when: "mysql_state == 'enabled'"
  changed_when: "True"
  notify: "restart mysql"
  update_resource:

    mysql.needs_restart: "yes"

- name: "restart mysql"
  when: "mysql_state == 'enabled'"
  notify: "set mysql.needs_restart to 'no'"
  sudo: "yes"
  action:

    module: "service"
    name: "mysql"
    state: "restarted"

- name: "set mysql.needs_restart to 'no'"
  changed_when: "True"
  update_resource:

    mysql.needs_restart: "no"

# ex: et ts=2 filetype=yaml
