---

- name: "install node.js"
  args:

    executable: "/bin/bash"
    creates: "{{ nodejs_flag }}"

  become: "yes"
  shell:

    set -euf -o pipefail;

    rm -rf {{ nodejs_tmp }};
    mkdir {{ nodejs_tmp }};
    cd {{ nodejs_tmp }};

    wget {{ nodejs_url }};

    rm -rf {{ nodejs_name }};
    tar --extract --xz --file {{ nodejs_archive }};

    rsync --archive --delete {{ nodejs_name }}/ {{ nodejs_target }}/;

    rm -rf {{ nodejs_tmp }};
    touch {{ nodejs_flag }};

# ex: et ts=2 filetype=yaml
