---

- name: "start master"
  when: "inventory_hostname == mysql_master"
  args:
    executable: "/bin/bash"
  shell:

    set -euf -o pipefail;

    sudo start mysql || true;

- name: "generate mysql replication password"
  update_resource:
    mysql.replication_password: "{{ 20 | generate_random }}"
  when: "mysql_replication_password is not defined"

- name: "create mysql replication user"
  when: "inventory_hostname == mysql_master"
  action:
    module: "mysql_user"
    name: "{{ mysql_replication_user }}"
    host: "%"
    password: "{{ mysql_replication_password }}"
    priv: "*.*:REPLICATION SLAVE"

- name: "get replication info from master"
  when: "inventory_hostname == mysql_master"
  args:
    executable: "/bin/bash"
  register: "mysql_master_status"
  shell:

    set -euf -o pipefail;

    mysql --skip-column-names --execute "
      SET GLOBAL innodb_fast_shutdown=0;
      FLUSH TABLES WITH READ LOCK;
      SHOW MASTER STATUS;
    " | sudo tee /tmp/mysql-master-status &

    sleep 0.1;

    test -s /tmp/mysql-master-status;

- name: "shut down master"
  when: "inventory_hostname == mysql_master"
  args:
    executable: "/bin/bash"
  shell:

    set -euf -o pipefail;

    sudo stop mysql || true;

    sleep 0.1;

- name: "shut down slave"
  when: "inventory_hostname != mysql_master"
  args:
    executable: "/bin/bash"
  shell:

    set -euf -o pipefail;

    sudo stop mysql || true;

- name: "synchronize data"
  when: "inventory_hostname != mysql_master"
  args:
    executable: "/bin/bash"
  shell:

    set -euf -o pipefail;

    sudo rsync --archive --delete
    root@{{ mysql_master }}:/var/lib/mysql/
    /var/lib/mysql/;

- name: "start master"
  when: "inventory_hostname == mysql_master"
  args:
    executable: "/bin/bash"
  shell:

    set -euf -o pipefail;

    sudo start mysql;

- name: "start slave"
  when: "inventory_hostname != mysql_master"
  args:
    executable: "/bin/bash"
  shell:

    set -euf -o pipefail;

    sudo start mysql;

- name: "configure replication"
  when: "inventory_hostname != mysql_master"
  args:
    executable: "/bin/bash"
  shell:

    set -euf -o pipefail;

    mysql --execute "

      CHANGE MASTER TO

      MASTER_HOST = '{{ mysql_master }}',
      MASTER_USER = '{{ mysql_replication_user }}',
      MASTER_PASSWORD = '{{ mysql_replication_password }}',

      MASTER_LOG_FILE = '{{
        hostvars [mysql_master].mysql_master_status.stdout.split ('\t') [0]
      }}',

      MASTER_LOG_POS = {{
        hostvars [mysql_master].mysql_master_status.stdout.split ('\t') [1]
      }};

    "

- name: "start replication"
  when: "inventory_hostname != mysql_master"
  args:
    executable: "/bin/bash"
  shell:

    set -euf -o pipefail;

    mysql --execute "
      START SLAVE;
    ";

- name: "shut down mysql"
  args:
    executable: "/bin/bash"
  shell:

    set -euf -o pipefail;

    sudo stop mysql || true;

# ex: et ts=2 filetype=yaml
