---

- name: "install mysql packages"
  action:
    module: "apt"
    name: "{{ item }}"
  sudo: "yes"
  with_items:

    - "mysql-server-5.5"
    - "python-mysqldb"

- name: "generate mysql root password"
  update_resource:
    mysql.root_password: "{{ 20 | generate_random }}"
  when: "mysql.root_password is not defined"

- name: "create mysql root user"
  action:
    module: "mysql_user"
    name: "root"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  when: "
    (
      mysql_replication == 'no'
      or inventory_hostname == mysql_master
    ) and mysql_state in [ 'installing', 'running' ]
  "

- name: "install mysql user config"
  sudo: "yes"
  when: "mysql_state in [ 'installing', 'running' ]"
  action:

    module: "template"
    src: "mysql-user-config"
    dest: "{{ item.home }}/.my.cnf"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0600"

  with_items:

    - user: "root"
      home: "/root"

    - user: "ubuntu"
      home: "/home/ubuntu"

- name: "disable mysql sysv init"
  sudo: "yes"
  register: "mysql_sysv_result"
  changed_when: "mysql_sysv_result.stdout != 'UNCHANGED'"
  shell:
    test -e /etc/init.d/mysql || { echo UNCHANGED; exit 0; };
    service mysql stop;
    rm -f /etc/init.d/mysql /etc/init.d/rc?.d/[KS]??mysql;

# ex: et ts=2 filetype=yaml
