---

- include: "icinga-web-core-install-check.yml"
  tags:

    - "icinga-web-core-install"
    - "icinga-web-core"
    - "icinga-web"
    - "icinga"

- include: "icinga-web-core-install.yml"
  tags:

    - "icinga-web-core-install"
    - "icinga-web-core"
    - "icinga-web"
    - "icinga"

# ex: et ts=2 filetype=yaml
