---

- name: "configure postgresql"
  with_items: "postgresql_config_templates"
  notify: "set postgresql.needs_restart to 'yes'"
  sudo: "yes"
  action:

    module: "template"
    dest: "{{ item.target }}"
    src: "{{ item.template }}"

    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"

- name: "set postgresql.state to 'enabled'"
  when: "postgresql_state == 'installed'"
  update_resource:

    postgresql.state: "enabled"

# ex: et ts=2 filetype=yaml
