---

- name: "install python dependencies"
  with_items:

    - "build-essential"
    - "libbz2-dev"
    - "libffi-dev"
    - "libgdm-dev"
    - "liblzma-dev"
    - "libncursesw5-dev"
    - "libreadline-dev"
    - "libssl-dev"
    - "libsqlite3-dev"
    - "zlib1g-dev"

  sudo: "yes"
  action:

    module: "apt"
    name: "{{ item }}"

- name: "build python"
  when: "python_installed_version != python_version"
  sudo: "yes"
  args:

    executable: "/bin/bash"

  shell:

    set -euf -o pipefail;

    rm -rf "{{ python_temp }}";
    mkdir -p "{{ python_temp }}";
    cd "{{ python_temp }}";

    wget --timeout=10 "{{ python_url }}";
    tar --extract --xz --file "{{ python_archive }}";
    cd "{{ python_name }}";

    ./configure
      --prefix="{{ python_target }}"
      --enable-shared
      --enable-ipv6
      --enable-unicode="ucs4"
      --with-dbmliborder="bdb:gdbm"
      --with-fpectl
      CC="x86_64-linux-gnu-gcc"
      CFLAGS="
        -g
        -D_FORTIFY_SOURCE=2
        -fstack-protector
        --param=ssp-buffer-size=4
        -Wformat
        -Werror=format-security
      "
      LDFLAGS="
        -Wl,-Bsymbolic-functions
        -Wl,-z,relro
        -Wl,--rpath={{ python_target }}/lib
      ";

    make install;

    cd /;
    rm -rf "{{ python_temp }}"

- name: "set python.installed_version"
  when: "python_version != python_installed_version"
  update_resource:

    python.installed_version: "{{ python_version }}"

- name: "set python.state to 'installed'"
  when: "python_state == ''"
  update_resource:

    python.state: "installed"

# ex: et ts=2 filetype=yaml
