---

# ---------- state

icinga_state: ""
icinga_installed_version: ""
icinga_needs_restart: ""
icinga_database_delegate: "{{ icinga_master }}"

# ---------- runtime defaults

icinga_common_name: "{{ identity_name }}"
icinga_alt_dns: [ "{{ icinga_common_name }}" ]  
icinga_alt_ips: []

icinga_database_type: ""
icinga_database_name: "icinga"
icinga_database_username: "icinga"
icinga_database_password: ""
icinga_database_initialized: "no"

icinga_ticket_salt: ""

icinga_ca_certificate: ""
icinga_certificate: ""
icinga_private_key: ""

icinga_graphite_enabled: ""
icinga_graphite_host: "localhost"
icinga_graphite_port: "2003"

# ---------- installation

icinga_mirror: "{{ wbs_dist }}/icinga"
icinga_directory: "icinga-{{ icinga_version }}"
icinga_archive: "{{ icinga_directory }}.tar.xz"
icinga_url: "{{ icinga_mirror }}/{{ icinga_archive }}"

icinga_temp: "/tmp/icinga-install"
icinga_target: "/opt/icinga-{{ icinga_version }}"

# ---------- master configuration

icinga_master_endpoints: "icinga-masters"
icinga_master_agents: "icinga-agents"
icinga_master_hosts: "icinga-hosts"

icinga_master_users: "icinga-users"
icinga_master_groups: "icinga-groups"

icinga_master_services: []

icinga_master_directories:

  - directory: "/etc/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/etc/icinga2/pki"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/etc/icinga2/scripts"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/etc/icinga2/zones.d"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/cache/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api/log"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api/repository"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api/zones"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/log/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

icinga_master_config_templates:

  - template: "icinga-master-commands"
    target: "commands.conf"
    mode: "0644"

  - template: "icinga-master-constants"
    target: "constants.conf"
    mode: "0644"

  - template: "icinga-master-hosts"
    target: "hosts.conf"
    mode: "0644"

  - template: "icinga-master-icinga"
    target: "icinga2.conf"
    mode: "0644"

  - template: "icinga-master-notifications"
    target: "notifications.conf"
    mode: "0644"

  - template: "icinga-master-script-mail"
    target: "scripts/mail"
    mode: "0755"

  - template: "icinga-master-secrets"
    target: "secrets.conf"
    mode: "0640"

  - template: "icinga-master-services"
    target: "services.conf"
    mode: "0644"

  - template: "icinga-master-time-periods"
    target: "time-periods.conf"
    mode: "0644"

  - template: "icinga-master-users"
    target: "users.conf"
    mode: "0644"

  - template: "icinga-master-zones"
    target: "zones.conf"
    mode: "0644"

icinga_master_security_files:

  - source: "{{ icinga_ca_certificate }}"
    target: "pki/ca.cert"
    mode: "0644"

  - source: "{{ icinga_certificate }}"
    target: "pki/{{ identity.name }}.cert"
    mode: "0644"

  - source: "{{ icinga_private_key }}"
    target: "pki/{{ identity.name }}.key"
    mode: "0640"

icinga_master_links:

  - link: "{{ icinga_target }}/etc"
    target: "../../etc"

  - link: "{{ icinga_target }}/var"
    target: "../../var"

# ---------- agent configuration

icinga_agent_masters: "icinga-masters"

icinga_master_directories:

  - directory: "/etc/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/etc/icinga2/pki"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/etc/icinga2/scripts"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/etc/icinga2/zones.d"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/cache/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api/log"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api/repository"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api/zones"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/log/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

icinga_agent_config_templates:

  - template: "icinga-agent-constants"
    target: "constants.conf"
    mode: "0644"

  - template: "icinga-agent-icinga"
    target: "icinga2.conf"
    mode: "0644"

  - template: "icinga-agent-secrets"
    target: "secrets.conf"
    mode: "0640"

  - template: "icinga-agent-zones"
    target: "zones.conf"
    mode: "0644"

icinga_agent_security_files:

  - source: "{{ icinga_ca_certificate }}"
    target: "pki/ca.cert"
    mode: "0644"

  - source: "{{ icinga_certificate }}"
    target: "pki/{{ identity.name }}.cert"
    mode: "0644"

  - source: "{{ icinga_private_key }}"
    target: "pki/{{ identity.name }}.key"
    mode: "0640"

icinga_agent_links:

  - link: "{{ icinga_target }}/etc"
    target: "../../etc"

  - link: "{{ icinga_target }}/var"
    target: "../../var"

icinga_host_vars: {}

# ex: et ts=2 filetype=yaml
