---

- name: "write etcd upstart config"
  sudo: "yes"
  action:
    module: "template"
    src: "etcd-upstart"
    dest: "/etc/init/etcd.conf"
  notify:
    - "reload upstart config"
    - "set etcd.needs_restart to 'yes'"

- name: "trigger etcd restart"
  when: "etcd.needs_restart == 'yes'"
  update_resource: {}
  changed_when: "True"
  notify: "restart etcd"

- meta: "flush_handlers"

# ex: et ts=2 filetype=yaml
