---

# ---------- general

php_install_version: ""
php_install: "{{ default_install | default ('yes') }}"
php_install_target: "/opt/php-{{ php_install_version }}"

php_config_directory: "{{ php_config_directory_map [php_install_version] }}"
php_config_directory_map:

  "5": "/etc/php5"
  "7.0": "/etc/php/7.0"

# ---------- state

php_fpm_socket: ""
php_needs_restart: ""
php_state: ""

php_installed_version: ""
php_installed_from: ""
php_installed_service: ""
php_installed_target: ""

# ---------- runtime config

php_memory_limit: "128M"

php_max_execution_time: "30"
php_max_input_time: "30"

php_upload_max_filesize: "2M"
php_post_max_size: "8M"
php_max_input_vars: "1000"

php_enabled_modules: []
php_disabled_modules: []

# ---------- install config

php_install_ppa_keys:

  - "E5267A6C"

php_install_ppas:

  - "deb http://ppa.launchpad.net/ondrej/php/ubuntu trusty main"
  - "deb-src http://ppa.launchpad.net/ondrej/php/ubuntu trusty main"

php_install_packages_core:

  - "php{{ php_install_version }}-cli"
  - "php{{ php_install_version }}-fpm"

php_install_packages_modules: []

php_install_packages: "{{ []
  | union (php_install_packages_core)
  | union (php_install_packages_modules)
}}"

# ---------- build config

php_build_temp: "/tmp/php-build"
php_build_mirror: "https://dist.wellbehavedsoftware.com/php"
php_build_name: "php-{{ php_version }}"
php_build_directory: "{{ php_build_name }}"
php_build_archive: "{{ php_build_name }}.tar.bz2"
php_build_url: "{{ php_build_mirror }}/{{ php_build_archive }}"

php_build_dependencies:

  - "apache2-dev"
  - "aspell"
  - "aspell-en"
  - "autoconf"
  - "automake"
  - "autotools-dev"
  - "bison"
  - "bsdmainutils"
  - "chrpath"
  - "comerr-dev"
  - "debhelper"
  - "dh-apparmor"
  - "dh-systemd"
  - "dictionaries-common"
  - "file"
  - "firebird-dev"
  - "firebird2.5-common"
  - "firebird2.5-common-doc"
  - "firebird2.5-server-common"
  - "flex"
  - "fontconfig-config"
  - "fonts-dejavu-core"
  - "freetds-common"
  - "freetds-dev"
  - "gettext"
  - "gettext-base"
  - "groff-base"
  - "icu-devtools"
  - "intltool-debian"
  - "krb5-multidev"
  - "language-pack-de"
  - "language-pack-de-base"
  - "libaio1"
  - "libapparmor-dev"
  - "libapparmor1"
  - "libapr1"
  - "libapr1-dev"
  - "libaprutil1"
  - "libaprutil1-dev"
  - "libaspell-dev"
  - "libaspell15"
  - "libasprintf0c2"
  - "libbison-dev"
  - "libbsd-dev"
  - "libbsd0"
  - "libbz2-dev"
  - "libc-client2007e"
  - "libc-client2007e-dev"
  - "libcroco3"
  - "libct4"
  - "libcurl3"
  - "libcurl4-openssl-dev"
  - "libdb-dev"
  - "libdb5.3-dev"
  - "libdbd-mysql-perl"
  - "libdbi-perl"
  - "libedit-dev"
  - "libedit2"
  - "libelfg0"
  - "libenchant-dev"
  - "libenchant1c2a"
  - "libevent-2.0-5"
  - "libevent-core-2.0-5"
  - "libevent-dev"
  - "libevent-extra-2.0-5"
  - "libevent-openssl-2.0-5"
  - "libevent-pthreads-2.0-5"
  - "libexpat1"
  - "libexpat1-dev"
  - "libfbclient2"
  - "libfbembed2.5"
  - "libfl-dev"
  - "libfontconfig1"
  - "libfontconfig1-dev"
  - "libfreetype6"
  - "libfreetype6-dev"
  - "libgcrypt11-dev"
  - "libgd-dev"
  - "libgd3"
  - "libglib2.0-0"
  - "libglib2.0-bin"
  - "libglib2.0-data"
  - "libglib2.0-dev"
  - "libgmp-dev"
  - "libgmp3-dev"
  - "libgmpxx4ldbl"
  - "libgnutls-dev"
  - "libgnutls-openssl27"
  - "libgnutlsxx27"
  - "libgpg-error-dev"
  - "libgssrpc4"
  - "libhunspell-1.3-0"
  - "libib-util"
  - "libice-dev"
  - "libice6"
  - "libicu-dev"
  - "libicu52"
  - "libidn11-dev"
  - "libjbig-dev"
  - "libjbig0"
  - "libjpeg-dev"
  - "libjpeg-turbo8"
  - "libjpeg-turbo8-dev"
  - "libjpeg8"
  - "libjpeg8-dev"
  - "libkadm5clnt-mit9"
  - "libkadm5srv-mit9"
  - "libkdb5-7"
  - "libkrb5-dev"
  - "libldap2-dev"
  - "libltdl-dev"
  - "libltdl7"
  - "liblzma-dev"
  - "libmagic-dev"
  - "libmagic1"
  - "libmcrypt-dev"
  - "libmcrypt4"
  - "libmhash-dev"
  - "libmhash2"
  - "libmysqlclient-dev"
  - "libmysqlclient18"
  - "libodbc1"
  - "libonig-dev"
  - "libonig2"
  - "libp11-kit-dev"
  - "libpam0g-dev"
  - "libpcre3-dev"
  - "libpcrecpp0"
  - "libperl5.18"
  - "libpipeline1"
  - "libpng12-dev"
  - "libpopt0"
  - "libpq-dev"
  - "libpq5"
  - "libpspell-dev"
  - "libpthread-stubs0-dev"
  - "libpython-stdlib"
  - "libpython2.7-minimal"
  - "libpython2.7-stdlib"
  - "libqdbm-dev"
  - "libqdbm14"
  - "librecode-dev"
  - "librecode0"
  - "librtmp-dev"
  - "libsasl2-dev"
  - "libsctp-dev"
  - "libsctp1"
  - "libsensors4"
  - "libsensors4-dev"
  - "libsigsegv2"
  - "libsm-dev"
  - "libsm6"
  - "libsnmp-base"
  - "libsnmp-dev"
  - "libsnmp30"
  - "libsqlite3-dev"
  - "libssl-dev"
  - "libsybdb5"
  - "libsystemd-daemon-dev"
  - "libsystemd-daemon0"
  - "libtasn1-6-dev"
  - "libterm-readkey-perl"
  - "libtext-iconv-perl"
  - "libtidy-0.99-0"
  - "libtidy-dev"
  - "libtiff5"
  - "libtiff5-dev"
  - "libtiffxx5"
  - "libtinfo-dev"
  - "libtool"
  - "libunistring0"
  - "libvpx-dev"
  - "libvpx1"
  - "libwebp-dev"
  - "libwebp5"
  - "libwebpdemux1"
  - "libwebpmux1"
  - "libwrap0"
  - "libwrap0-dev"
  - "libx11-6"
  - "libx11-data"
  - "libx11-dev"
  - "libxau-dev"
  - "libxau6"
  - "libxcb1"
  - "libxcb1-dev"
  - "libxdmcp-dev"
  - "libxdmcp6"
  - "libxml2"
  - "libxml2-dev"
  - "libxmlrpc-epi-dev"
  - "libxmlrpc-epi0"
  - "libxmltok1"
  - "libxmltok1-dev"
  - "libxpm-dev"
  - "libxpm4"
  - "libxslt1-dev"
  - "libxslt1.1"
  - "libxt-dev"
  - "libxt6"
  - "libzip-dev"
  - "libzip2"
  - "locales"
  - "m4"
  - "man-db"
  - "mime-support"
  - "mlock"
  - "mysql-client-5.5"
  - "mysql-client-core-5.5"
  - "mysql-common"
  - "mysql-server"
  - "mysql-server-5.5"
  - "mysql-server-core-5.5"
  - "netbase"
  - "netcat-traditional"
  - "odbcinst"
  - "odbcinst1debian2"
  - "pkg-config"
  - "po-debconf"
  - "psmisc"
  - "python"
  - "python-minimal"
  - "python2.7"
  - "python2.7-minimal"
  - "re2c"
  - "systemtap-sdt-dev"
  - "ucf"
  - "unixodbc"
  - "unixodbc-dev"
  - "uuid-dev"
  - "x11-common"
  - "x11proto-core-dev"
  - "x11proto-input-dev"
  - "x11proto-kb-dev"
  - "xorg-sgml-doctools"
  - "xtrans-dev"
  - "zlib1g-dev"

# ex: et ts=2 filetype=yaml
